import React from "react";
import { BrowserRouter as Router, Routes, Route, Navigate } from "react-router-dom";
import Navbar from "./Navbar";
import HeroSection from "./HeroSection";
import Features from "./Features";
import Dashboard from "./Dashboard";
import Portfolio from "./Portfolio";
import InstitutionDashboard from "./InstitutionDashboard";
import Footer from "./Footer";
import Login from "./Login";   
import StudentPortfolio from "./StudentPortfolio";
import ActivityTracker from "./ActivityTracker";
import { auth } from "./firebase";  
import FacultyApprovalPanel from "./FacultyApprovalPanel";
import AutoGeneratedPortfolio from "./AutoGeneratedPortfolio";
import AnalyticsReporting from "./AnalyticsReporting";
import IntegrationSupport from "./IntegrationSupport";


function PrivateRoute({ children }) {
  const user = auth.currentUser; 
  return user ? children : <Navigate to="/login" />;
}

export default function App() {
  return (
    <Router>
      <div className="font-sans scroll-smooth min-h-screen flex flex-col">
        <Navbar />
        <Routes>
          
          <Route
            path="/"
            element={
              <>
                <HeroSection />
                <div id="features">
                  <Features />
                  <Dashboard />
                  <Portfolio />
                  <InstitutionDashboard />
                  
                  <Footer />
                </div>
              </>
            }
          />

          
          <Route
            path="/login"
            element={<Login onBack={() => window.history.back()} />}
          />
          
          
          
          
           <Route path="/" element={<Features />} />
           <Route path="/StudentDashboard" element={<StudentPortfolio/>} />
        <Route path="/activity-tracker" element={<ActivityTracker />} />
        <Route path="/faculty-approval" element={<FacultyApprovalPanel />} />
        <Route path="/auto-portfolio" element={<AutoGeneratedPortfolio />} />
        <Route path="/analytics" element={<AnalyticsReporting />} />
        <Route path="/IntegrationSupport" element={<IntegrationSupport />} />
        </Routes>
      </div>
    </Router>
  );
}
